version: '2.2'

services:
  videostream:
    container_name: videostream
    build:
      context: ./videostream
    volumes:
      - station_data:/var/azuracast/stations
    restart: always
    logging:
      options: 
        max-size: "1m"
        max-file: "5"
    environment:
      # VS_VBR: 1500k
      # VS_FPS: 30
      # VS_QUALITY: superfast
      VS_RTMP_SERVER: rtmp://a.rtmp.youtube.com/live2/aaaa-bbbb-cccc-dddd
      # VS_FONT_FILE: /usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf
      VS_TEXT_SOURCE: /var/azuracast/stations/azuratest_radio/config/nowplaying.txt
      # VS_TEXT_X: 315
      # VS_TEXT_Y: 960
      VS_AUDIO_SOURCE: http://stations:8000/radio.mp3
      VS_VIDEO_SOURCE: /var/azuracast/videostream/example.mp4